version: 2
jobs:
  one:
  # working_directory: ~/build
    machine:
      image: circleci/classic:edge
    steps:
      - checkout # this pulls pulls code down from GitHub
      - run: echo "A first hello" # This prints "A first hello" to stdout.
      - run: sleep 25 # a command telling the job to "sleep" for 25 seconds
  two:
   # working_directory: ~/build
    machine:
      image: circleci/classic:edge
    steps:
      - checkout # this pulls pulls code down from GitHub
      - run: echo "A more familiar hi" # This prints A first hello to stdout.
      - run: sleep 15 # a command telling the job to "sleep" for 25 seconds
workflows:
   version: 2
   one_and_two: # this is the name of our workflow
     jobs: # and here we list the jobs we are going to run.
       - one
       - two
